<a href="https://colab.research.google.com/github/sanvi-pathare/Heart-Attack-Prediction/blob/main/heat_attack_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df= pd.read_csv('/content/drive/MyDrive/data.csv')
df

Mounted at /content/drive


age  sex  cp trestbps chol fbs restecg thalach exang  oldpeak slope ca  \
0     28    1   2      130  132   0       2     185     0      0.0     ?  ?   
1     29    1   2      120  243   0       0     160     0      0.0     ?  ?   
2     29    1   2      140    ?   0       0     170     0      0.0     ?  ?   
3     30    0   1      170  237   0       1     170     0      0.0     ?  ?   
4     31    0   2      100  219   0       1     150     0      0.0     ?  ?   
..   ...  ...  ..      ...  ...  ..     ...     ...   ...      ...   ... ..   
289   52    1   4      160  331   0       0      94     1      2.5     ?  ?   
290   54    0   3      130  294   0       1     100     1      0.0     2  ?   
291   56    1   4      155  342   1       0     150     1      3.0     2  ?   
292   58    0   2      180  393   0       0     110     1      1.0     2  ?   
293   65    1   4      130  275   0       1     115     1      1.0     2  ?   

    thal  num         
0      ?           0  
1      ?           0  
2      ?           0  
3      6           0  
4      ?           0  
..   ...         ...  
289    ?           1  
290    ?           1  
291    ?           1  
292    7           1  
293    ?           1  

[294 rows x 14 columns]

In [ ]:
df.replace('?', np.nan, inplace=True)

In [ ]:
df.isnull().sum()

age             0
sex             0
cp              0
trestbps        1
chol           23
fbs             8
restecg         1
thalach         1
exang           1
oldpeak         0
slope         190
ca            291
thal          266
num             0
dtype: int64

In [ ]:
for i in df.columns:
    if df[i].dtype == 'object':
        df[i] = df[i].fillna(df[i].mode()[0])
    else:
        df[i] = df[i].fillna(df[i].median())

In [ ]:
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
num           0
dtype: int64

In [ ]:
df.dtypes

age             int64
sex             int64
cp              int64
trestbps        int64
chol            int64
fbs             int64
restecg         int64
thalach         int64
exang           int64
oldpeak       float64
slope           int64
ca              int64
thal            int64
num             int64
dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=['num       '])
y = df['num       ']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("logistic regression")
print("accuracy:", accuracy_score(y_test, y_pred_lr))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred_lr))
print("classification report:\n", classification_report(y_test, y_pred_lr))

logistic regression
accuracy: 0.7966101694915254
confusion matrix:
 [[31  7]
 [ 5 16]]
classification report:
               precision    recall  f1-score   support

           0       0.86      0.82      0.84        38
           1       0.70      0.76      0.73        21

    accuracy                           0.80        59
   macro avg       0.78      0.79      0.78        59
weighted avg       0.80      0.80      0.80        59



In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("random forest")
print("accuracy:", accuracy_score(y_test, y_pred_rf))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("classification report:\n", classification_report(y_test, y_pred_rf))

random forest
accuracy: 0.8135593220338984
confusion matrix:
 [[32  6]
 [ 5 16]]
classification report:
               precision    recall  f1-score   support

           0       0.86      0.84      0.85        38
           1       0.73      0.76      0.74        21

    accuracy                           0.81        59
   macro avg       0.80      0.80      0.80        59
weighted avg       0.82      0.81      0.81        59



In [ ]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

print("support vector machine")
print("accuracy:", accuracy_score(y_test, y_pred_svm))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("classification report:\n", classification_report(y_test, y_pred_svm))

support vector machine
accuracy: 0.864406779661017
confusion matrix:
 [[35  3]
 [ 5 16]]
classification report:
               precision    recall  f1-score   support

           0       0.88      0.92      0.90        38
           1       0.84      0.76      0.80        21

    accuracy                           0.86        59
   macro avg       0.86      0.84      0.85        59
weighted avg       0.86      0.86      0.86        59

